apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: deadmanssnitch-operator
  annotations:
    name: annotation
spec:
  scopes:
  - Cluster
  phases:
  - name: cleanup-deploy
  - name: cleanup-rbac
  - name: crds
  - name: namespace
  - name: rbac
  - name: deploy
  - name: integrations
  availabilityProbes:
  - probes:
    - condition:
        type: Available
        status: 'True'
    - fieldsEqual:
        fieldA: .status.updatedReplicas
        fieldB: .status.replicas
    selector:
      kind:
        group: apps
        kind: Deployment
  config:
    openAPIV3Schema:
      properties:
        image:
          description: Operator image to deploy
          type: string
          default: None
        silentAlertLegalEntityIds:
          description: Legal entity IDs to exclude from Dead Man's Snitch monitoring
          type: array
          items:
            type: string
          default: []
        deadmanssnitchOsdTags:
          description: Tags to apply to OSD Dead Man's Snitch integrations
          type: array
          items:
            type: string
          default: []
        fedramp:
          description: Enable FedRAMP mode
          type: string
          default: "false"
      type: object
