apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: deadmanssnitch-operator
  annotations:
    name: annotation
spec:
  scopes:
  - Cluster
  phases:
  - name: cleanup-deploy
  - name: cleanup-rbac
  - name: crds
  - name: rbac
  - name: deploy
  - name: integrations
  availabilityProbes:
  - probes:
    - condition:
        type: Available
        status: 'True'
    - fieldsEqual:
        fieldA: .status.updatedReplicas
        fieldB: .status.replicas
    selector:
      kind:
        group: apps
        kind: Deployment
  config:
    openAPIV3Schema:
      properties:
        image:
          description: Operator image to deploy
          type: string
          default: None
        silentAlertLegalEntityIds:
          description: Legal entity IDs to exclude from Dead Man's Snitch monitoring
          type: array
          items:
            type: string
          default: []
        deadmanssnitchOsdTags:
          description: Tags to apply to OSD Dead Man's Snitch integrations
          type: array
          items:
            type: string
          default: []
        fedramp:
          description: Enable FedRAMP mode
          type: string
          default: "false"
      type: object
test:
  template:
  - name: default
    context:
      package:
        metadata:
          name: deadmanssnitch-operator
          namespace: deadmanssnitch-operator
      config:
        image: quay.io/example/deadmanssnitch-operator:test
        fedramp: "false"
        silentAlertLegalEntityIds:
        - "1aV37K1VQv2zSStwSkdwBNOUBGI"
        - "2Mo8exhgEA5ir1lsVypXUb9v902"
        deadmanssnitchOsdTags:
        - "hive-production"
  - name: empty-silent-ids
    context:
      package:
        metadata:
          name: deadmanssnitch-operator
          namespace: deadmanssnitch-operator
      config:
        image: quay.io/example/deadmanssnitch-operator:test
        fedramp: "false"
        silentAlertLegalEntityIds: []
        deadmanssnitchOsdTags:
        - "hive-int"
  - name: fedramp
    context:
      package:
        metadata:
          name: deadmanssnitch-operator
          namespace: deadmanssnitch-operator
      config:
        image: quay.io/example/deadmanssnitch-operator:test
        fedramp: "true"
        silentAlertLegalEntityIds: []
        deadmanssnitchOsdTags:
        - "hive-production"
