apiVersion: v1
kind: Namespace
metadata:
  name: deadmanssnitch-operator
  labels:
    openshift.io/workload-monitoring: "true"
  annotations:
    package-operator.run/phase: namespace
    package-operator.run/collision-protection: IfNoController
