apiVersion: v1
kind: Template
metadata:
  name: olm-artifacts-template

parameters:
- name: REGISTRY_IMG
  required: true
- name: CHANNEL
  value: staging
- name: IMAGE_TAG
  value: latest
- name: SILENT_ALERT_LEGALENTITY_IDS
  value: '["None"]'
- name: DEADMANSSNITCH_OSD_TAGS
  required: true

objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    name: deadmanssnitch-operator-catalog
  spec:
    sourceType: grpc
    image: ${REGISTRY_IMG}:${CHANNEL}-${IMAGE_TAG}
    displayName: deadmanssnitch-operator Registry
    publisher: SRE 

- apiVersion: operators.coreos.com/v1alpha2
  kind: OperatorGroup
  metadata:
    name: deadmanssnitch-operator-og
  spec:
    targetNamespaces:
    - deadmanssnitch-operator

- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: deadmanssnitch-operator
  spec:
    channel: ${CHANNEL}
    name: deadmanssnitch-operator
    source: deadmanssnitch-operator-catalog
    sourceNamespace: deadmanssnitch-operator

- apiVersion: deadmanssnitch.managed.openshift.io/v1alpha1
  kind: DeadmansSnitchIntegration
  metadata:
    name: osd
  spec:
    snitchNamePostFix: ""
    dmsAPIKeySecretRef:
      name: deadmanssnitch-api-key
      namespace: deadmanssnitch-operator
    clusterDeploymentSelector:
      matchExpressions:
      # only create DMS service for managed (OSD) clusters
      - key: api.openshift.com/managed
        operator: In
        values: ["true"]
      # ignore CD w/ "legacy" noalerts label
      - key: api.openshift.com/noalerts
        operator: NotIn
        values: ["true"]
      # ignore CD w/ ext noalerts label
      - key: ext-managed.openshift.io/noalerts
        operator: NotIn
        values: ["true"]
      # ignore CD for specific organizations
      - key: api.openshift.com/legal-entity-id
        operator: NotIn
        values: ${{SILENT_ALERT_LEGALENTITY_IDS}}
      # ignore CD for any "nightly" clusters
      - key: api.openshift.com/channel-group
        operator: NotIn
        values: ["nightly"]
    targetSecretRef:
      name: dms-secret
      namespace: openshift-monitoring
    tags: ${{DEADMANSSNITCH_OSD_TAGS}}
    clusterDeploymentAnnotationsToSkip:
    - name: hive.openshift.io/fake-cluster
      value: "true"
