apiVersion: v1
kind: Template
parameters:
  - name: CHANNEL
    required: false
  - name: PKO_IMAGE
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE_DIGEST
    required: true
  - name: NAMESPACE
    value: openshift-deadmanssnitch-operator
  - name: REPO_NAME
    value: deadmanssnitch-operator
    required: true
metadata:
  name: selectorsyncset-template
objects:
  - apiVersion: hive.openshift.io/v1
    kind: SelectorSyncSet
    metadata:
      labels:
        managed.openshift.io/gitHash: ${IMAGE_TAG}
        managed.openshift.io/gitRepoName: ${REPO_NAME}
        managed.openshift.io/osd: "true"
      name: deadmanssnitch-operator-stage
    spec:
      clusterDeploymentSelector:
        matchLabels:
          api.openshift.com/managed: "true"
      resourceApplyMode: Sync
      resources:
        - apiVersion: package-operator.run/v1alpha1
          kind: ClusterPackage
          metadata:
            name: "${REPO_NAME}"
            annotations:
              package-operator.run/collision-protection: IfNoController
          spec:
            image: ${PKO_IMAGE}:${IMAGE_TAG}
