apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: deadmanssnitch-operator-0.0.2
  namespace: placeholder
  annotations:
    categories: A list of comma separated categories that your operator falls under.
    certified: "false"
    description: Dead Mans Snitch Operator. This operator manages Deadmansnicthes for OSD Clusters.
    containerImage: quay.io/app-sre/deadmanssnitch-operator:latest
    createdAt: "2019-04-10T17:34:33Z"
    support: Matt Woodson
spec:
  displayName: deadmanssnitch-operator
  description: Dead Mans Snitch Operator.
  keywords:
  - kubernetes
  - openshift
  - multi-cluster
  - cluster
  version: 0.0.2
  provider:
    name: Red Hat, Inc
  maturity: alpha
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: false
  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: deadmanssnitch-operator
        # Rules will be added here by the generate-operator-bundle.py script.
      deployments:
      - name: deadmanssnitch-operator
        # Deployment spec will be added here by the generate-operator-bundle.py script.
  customresourcedefinitions:
    owned:
    - description: DeadmansSnitchIntegration
      displayName: DeadmansSnitchIntegration
      kind: DeadmansSnitchIntegration
      name: deadmanssnitchintegrations.deadmanssnitch.managed.openshift.io
      version: v1alpha1
